name: Benchmarks
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: benchmarks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    if: >-
      ${{
        github.event_name == 'push' ||
        (
          github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name, 'ci:run-benchmarks') &&
          github.event.pull_request.state == 'open'
        )
      }}

    uses: ./.github/workflows/interface-unit-tests.yml
    with:
      branch: ${{ github.ref }}

      run_benchmarks_ci: true
