name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'Hi there! This issue has not been updated for 60 days, and will be closed in 7 days. To keep it open, please update the issue or remove the label.'
          stale-pr-message: 'Hi there! This PR has not been updated for 60 days, and will be closed in 7 days. To keep it open, please update the PR or remove the label.'
          days-before-stale: 60
          days-before-issue-stale: -1
          exempt-pr-labels: keep-open
          start-date: '2023-12-05T00:00:00Z'
